// Every string shown on screen lives here (brief NFR-3). Default: Vietnamese. To add Japanese/English,
// add another object with the same shape and switch `t`; components never hard-code display text.

export const vi = {
  app: {
    name: "SME CI Agent",
    tagline: "Cải tiến liên tục cho xưởng sản xuất",
    sandbox: "Dữ liệu mô phỏng (synthetic)",
  },
  nav: {
    sectionRun: "Vận hành",
    sectionData: "Dữ liệu và học tập",
    run: "Phiên chạy",
    runs: "Lịch sử run",
    overview: "Tổng quan KPI",
    kaizen: "Bài học và chỉ số",
    audit: "Nhật ký và SOP",
  },
  topbar: {
    present: "Trình chiếu",
    exitPresent: "Thoát trình chiếu",
    presentHint: "Phím F: bật/tắt chế độ trình chiếu",
    themeLight: "Giao diện sáng",
    themeDark: "Giao diện tối",
    menu: "Mở menu",
    role: "Người duyệt (demo)",
  },
  source: {
    live: "Trực tiếp",
    replay: "Phát lại",
    sse: "Theo dõi",
    replayBanner: "PHÁT LẠI bản ghi, không gọi backend. Các nút chỉ mô phỏng.",
    mockBanner: "Dữ liệu mẫu đúng hình dạng API; sẽ thay bằng API thật (R10a).",
    connection: {
      idle: "Chưa kết nối",
      connecting: "Đang kết nối…",
      open: "Đã kết nối",
      closed: "Luồng đã đóng",
      disconnected: "Mất kết nối",
    } as Record<string, string>,
  },
  steps: {
    detect: "Phát hiện",
    investigate: "Điều tra",
    ask: "Hỏi người",
    improve: "Đề xuất",
    act: "Áp dụng",
    measure: "Đo KPI",
    learn: "Học",
    rollback: "Rollback",
  } as Record<string, string>,
  stepHints: {
    detect: "Quét KPI bằng thống kê",
    investigate: "Đọc log, tìm tương quan",
    ask: "Thiếu bằng chứng thì hỏi",
    improve: "Hành động + SOP mới",
    act: "Sau khi người duyệt",
    measure: "So KPI trước / sau",
    learn: "Lưu phiếu kaizen",
    rollback: "Quay về SOP trước",
  } as Record<string, string>,
  status: {
    idle: "Sẵn sàng",
    running: "Agent đang chạy",
    waitAnswer: "Chờ bạn trả lời",
    waitApproval: "Chờ bạn duyệt",
    waitRollback: "Chờ xác nhận rollback",
    halted: "Đã dừng, chờ bạn",
    completed: "Hoàn tất, đã học",
    completedNoLearn: "Hoàn tất",
    closed: "Đã đóng bởi người",
    noAnomaly: "Không có bất thường",
    error: "Lỗi",
  },
  start: {
    title: "Phân tích dữ liệu vận hành",
    lead: "Agent quét 6 tháng KPI của 3 lò hàn reflow, tự điều tra khi thấy bất thường và đề xuất cải tiến. Mọi thay đổi đều chờ bạn duyệt.",
    button: "Bắt đầu phân tích",
    advanced: "Tuỳ chọn nâng cao",
    changeTime: "Thời điểm áp dụng thay đổi (ISO, để trống = tự chọn)",
    replayLink: "Hoặc phát lại một bản ghi",
    facts: ["3 máy · 3 ca/ngày", "6 tháng dữ liệu", "Agent chỉ đọc dữ liệu"],
  },
  thinking: {
    title: "Agent đang làm việc",
    messages: [
      "Đang quét KPI và giới hạn kiểm soát…",
      "Đang đọc log máy…",
      "Đang đối chiếu lịch ca…",
      "Đang tìm tương quan giữa KPI và các tín hiệu…",
      "Đang cân nhắc các giả thuyết theo Ishikawa…",
      "Đang soạn đề xuất và SOP mới…",
    ],
    applying: "Đang áp dụng thay đổi và đo KPI…",
    sending: "Đang gửi…",
    note: "Một vòng với LLM thật mất khoảng 15–20 giây.",
  },
  anomaly: {
    title: "Bất thường được phát hiện",
    machine: "Máy",
    shift: "Ca",
    since: "Từ",
    current: "Hiện tại",
    baseline: "Mức nền",
    limit: "Giới hạn trên",
    points: "Số điểm vượt",
    planned: "Có kế hoạch",
    none: "Chưa phát hiện bất thường.",
  },
  activity: {
    title: "Hoạt động của agent",
    empty: "Agent chưa gọi công cụ nào.",
    ok: "Xong",
    failed: "Lỗi",
    found: (n: number) => `Tìm thấy ${n} bất thường`,
  },
  tools: {
    detect: "Quét KPI",
    query_logs: "Đọc log máy",
    correlate: "Tìm tương quan",
    get_shift_schedule: "Xem lịch ca",
    read_sop: "Đọc SOP",
    fetch_kpi_breakdown: "Xem phân rã KPI",
  } as Record<string, string>,
  toolArgs: {
    machine_id: "Máy",
    kpi: "KPI",
    source: "Nguồn",
    start: "Từ",
    end: "Đến",
    sop_id: "SOP",
    hypotheses: "Giả thuyết",
    shift: "Ca",
  } as Record<string, string>,
  hypotheses: {
    title: "Giả thuyết (Ishikawa)",
    empty: "Chưa có giả thuyết.",
    leading: "Dẫn đầu",
    confidence: "Độ tin cậy",
    insufficient: "Chưa đủ bằng chứng",
  },
  // display names of KPI codes from data/context_profile.yaml; unknown codes are shown as they are
  kpis: {
    defect_rate: "Tỷ lệ lỗi",
    rework_rate: "Tỷ lệ làm lại",
  } as Record<string, string>,
  groups: {
    machine: "Máy móc",
    method: "Phương pháp",
    material: "Nguyên vật liệu",
    environment: "Môi trường",
    people: "Con người",
  } as Record<string, string>,
  causes: {
    wrong_setpoint: "Setpoint bị đổi sai so với SOP",
    wear: "Hao mòn thiết bị",
    calibration: "Sai lệch hiệu chuẩn",
    outdated_sop: "SOP lỗi thời",
    missing_check: "Thiếu bước kiểm tra",
    material_batch: "Lô nguyên liệu",
    ambient_temperature: "Nhiệt độ môi trường",
    new_operator: "Người vận hành mới",
    training_gap: "Thiếu đào tạo",
    "unclear cause": "Chưa rõ nguyên nhân",
  } as Record<string, string>,
  question: {
    title: "Agent cần thêm thông tin",
    lead: "Bằng chứng chưa đủ để kết luận. Agent hỏi thay vì đoán.",
    attempt: (a: number, m: number) => `Lần hỏi ${a}/${m}`,
    evidenceTitle: "Chưa đủ dữ liệu sau thay đổi",
    evidenceLead: "Agent không kết luận khi có quá ít điểm đo; xác nhận để đo lại khi có thêm dữ liệu.",
    label: "Câu trả lời của bạn",
    placeholder: "Ví dụ: ca đêm hôm đó có người thay ca; lô nguyên liệu không đổi…",
    send: "Gửi câu trả lời",
    fallback: "Agent cần thêm thông tin.",
  },
  proposal: {
    title: "Agent đề xuất thay đổi, cần bạn duyệt",
    why: "Vì sao",
    what: "Làm gì",
    sop: "SOP cũ → mới",
    expect: "Kỳ vọng",
    decide: "Quyết định của bạn",
    evidence: (refs: string) => `Dựa trên bằng chứng ${refs}`,
    machineAction: "Máy",
    sopUnchanged: "Nội dung SOP không đổi",
    sopCurrent: "Bản hiện tại",
    sopNew: "Bản đề xuất",
    sopNotAvailable: "(không có nội dung bản hiện tại)",
    linesAdded: (n: number) => `+${n} dòng`,
    linesRemoved: (n: number) => `−${n} dòng`,
    more: "Xem thêm",
    less: "Thu gọn",
    kpiDecrease: "giảm về",
    kpiIncrease: "tăng lên",
    target: "mục tiêu",
  },
  rollback: {
    title: "KPI không đạt, đề xuất quay về SOP trước",
    lead: "Thay đổi đã áp dụng chưa đưa KPI về ngưỡng. Xác nhận sẽ khôi phục nội dung SOP trước thành một phiên bản mới; giữ nguyên thì SOP đã áp dụng vẫn hiệu lực.",
    inForce: "Đang hiệu lực",
    restore: "Sẽ khôi phục",
  },
  halt: {
    title: "Run đã dừng, chờ bạn quyết định",
    lead: "Không có gì thay đổi cho đến khi bạn chọn. Có thể bổ sung thông tin ở ô lý do trước khi điều tra lại.",
    reasons: {
      max_questions_reached: "Đã hỏi đủ số lần cho phép",
      insufficient_evidence: "Chưa đủ bằng chứng sau nhiều lần chờ",
      rollback_declined: "Bạn đã giữ SOP hiện tại",
      max_rollbacks_reached: "Đã rollback tối đa",
      max_total_rollbacks_reached: "Đã chạm tổng số rollback của run",
      max_rejections_reached: "Đã từ chối tối đa",
      max_revisions_reached: "Đã bác bỏ / bổ sung tối đa",
    } as Record<string, string>,
    sopInForce: (sop: string) => `SOP ${sop} đang hiệu lực.`,
  },
  decision: {
    approver: "Người duyệt",
    approverPlaceholder: "Chọn người duyệt",
    approverNotListed: (n: string) => `"${n}" không có trong danh sách người duyệt.`,
    reason: "Lý do / thông tin bổ sung",
    reasonPlaceholder: "Không bắt buộc khi duyệt hoặc từ chối",
    reviseHint: "Muốn bác bỏ giả thuyết hoặc bổ sung thông tin: ghi vào ô lý do trước.",
    lockedHint: "Chọn người duyệt để mở khoá các nút.",
    approve: "Duyệt",
    reject: "Từ chối",
    revise: "Bác bỏ giả thuyết / bổ sung thông tin",
    approveRollback: "Xác nhận rollback",
    rejectRollback: "Giữ SOP hiện tại",
    investigate: "Điều tra lại",
    finish: "Kết thúc run",
    conflict: "Đề xuất đã thay đổi, hãy xem lại.",
  },
  measure: {
    title: "Kết quả đo KPI",
    before: "Trước",
    after: "Sau",
    target: "Mục tiêu",
    passed: "Đạt",
    failed: "Chưa đạt",
    samples: (b: number | null, a: number | null, d: number | null) =>
      `${b ?? "–"} điểm trước · ${a ?? "–"} điểm sau${d ? ` · cửa sổ ${d} ngày` : ""}`,
    insufficient: "Chưa đủ dữ liệu sau thay đổi",
    insufficientDetail: (n: number | null, m: number | null) => `${n ?? 0} / ${m ?? "?"} điểm cần thiết`,
    notApplied: "Chưa áp dụng thay đổi",
    tolerance: (t: number) => `dung sai ${Math.round(t * 100)}%`,
    history: "Các lần đo",
  },
  outcome: {
    completedTitle: "Vòng cải tiến đã khép lại",
    completedLead: "Thay đổi được duyệt, KPI về ngưỡng và bài học đã được lưu.",
    closedTitle: "Run đã được đóng",
    closedLead: "Bạn đã kết thúc run. Không có thay đổi nào khác được áp dụng.",
    noAnomalyTitle: "Không phát hiện bất thường",
    noAnomalyLead: "KPI của mọi máy nằm trong giới hạn kiểm soát. Agent không gọi LLM.",
    newRun: "Bắt đầu run mới",
  },
  kaizen: {
    title: "Phiếu kaizen",
    problem: "Vấn đề",
    cause: "Nguyên nhân gốc",
    action: "Biện pháp",
    result: "Kết quả",
    sop: "SOP",
    outcome: { success: "Thành công", no_change: "Không đổi" } as Record<string, string>,
    empty: "Chưa có bài học nào.",
  },
  error: {
    title: "Run dừng vì lỗi",
    retry: "Thử lại",
    retrying: "Đang thử lại…",
    notRetryable: "Đã thử lại tối đa; không thể thử tiếp. Hãy bắt đầu run mới.",
    past: (e: string) => `Đã thử lại sau lỗi: ${e}`,
    api: "Không gửi được",
    invalidEvents: (n: number) => `${n} sự kiện không hợp lệ đã bị bỏ qua`,
  },
  log: {
    title: "Nhật ký sự kiện",
    empty: "Chưa có sự kiện.",
    details: "Chi tiết",
    hide: "Ẩn",
  },
  events: {
    anomaly_detected: "Phát hiện bất thường",
    hypothesis_updated: "Cập nhật giả thuyết",
    tool_called: "Gọi công cụ",
    question_asked: "Agent đặt câu hỏi",
    answer_received: "Người trả lời",
    proposal_created: "Tạo đề xuất",
    approval_decided: "Người quyết định",
    sop_applied: "Áp dụng SOP",
    kpi_measured: "Đo KPI",
    rollback_done: "Rollback",
    learning_saved: "Lưu bài học",
    run_finished: "Kết thúc run",
  } as Record<string, string>,
  agents: {
    quality: "Chất lượng",
    investigation: "Điều tra",
    improvement: "Cải tiến",
    system: "Hệ thống",
  } as Record<string, string>,
  decisions: {
    approved: "duyệt",
    rejected: "từ chối",
    revise: "bác bỏ / bổ sung",
    investigate: "điều tra lại",
    finish: "kết thúc",
  } as Record<string, string>,
  replay: {
    title: "Phát lại",
    file: "Bản ghi",
    speed: "Tốc độ",
    pause: "Tạm dừng",
    play: "Phát",
    restart: "Phát lại từ đầu",
    simulated: "(mô phỏng)",
    files: {
      "run-happy": "Hỏi người → duyệt → KPI đạt → học",
      "run-rollback": "Sửa sai → rollback → điều tra lại → đạt",
      "run-rollback-declined": "Giữ SOP, không rollback → dừng",
      "run-insufficient-evidence": "Chưa đủ dữ liệu sau thay đổi",
      "run-revise": "Bác bỏ giả thuyết → đề xuất lại",
      "run-halt-max-questions": "Hỏi quá số lần → dừng",
      "run-error-retry": "LLM lỗi → thử lại",
      "run-no-anomaly": "Không có bất thường",
      scenario1: "Kịch bản 1 (fixture cũ, chỉ sự kiện)",
    } as Record<string, string>,
  },
  runs: {
    title: "Lịch sử run",
    lead: "Các run đã ghi lại. Bấm để phát lại đúng như khi chạy thật.",
    search: "Tìm theo id hoặc nhánh…",
    columns: { id: "Run", branch: "Diễn biến", result: "Kết quả", events: "Sự kiện", when: "Thời điểm", actions: "" },
    open: "Phát lại",
    empty: "Không có run phù hợp.",
  },
  overview: {
    title: "Tổng quan KPI",
    lead: "Tỷ lệ lỗi theo ca của từng máy trong 6 tháng mô phỏng. Vùng tô là bất thường mà Detect tìm thấy.",
    machine: "Máy",
    shift: "Ca",
    allShifts: "Mọi ca",
    baseline: "Mức nền",
    limit: "Giới hạn trên",
    anomaly: "Bất thường",
    value: "Tỷ lệ lỗi",
    stats: { current: "Trung bình 7 ngày cuối", baseline: "Mức nền", limit: "Giới hạn trên", anomalies: "Bất thường" },
  },
  kaizenPage: {
    title: "Bài học và 3 chỉ số",
    lead: "Mỗi vòng khép kín để lại một phiếu kaizen. Ba chỉ số so sánh trước và sau khi agent hoạt động.",
    metrics: "3 chỉ số trước / sau",
    defect: "Tỷ lệ lỗi",
    mttd: "MTTD (phát hiện)",
    mttr: "MTTR (khắc phục)",
    recurrence: "Tỷ lệ tái diễn",
    beforeAgent: "Trước agent",
    withAgent: "Có agent",
    pending: "Chờ số liệu thật (T-042)",
    cards: "Phiếu kaizen",
  },
  audit: {
    title: "Nhật ký và phiên bản SOP",
    lead: "Agent chỉ đọc dữ liệu. Mọi thay đổi có người duyệt, có phiên bản và nằm trong nhật ký.",
    who: "Ai",
    what: "Hành động",
    when: "Lúc",
    run: "Run",
    detail: "Chi tiết",
    versions: "Phiên bản SOP",
    view: "Xem nội dung",
    applied: (v: number) => `Áp dụng v${v}`,
    restored: (v: number, from: number) => `Rollback: v${v} khôi phục từ v${from}`,
    empty: "Chưa có mục nào.",
  },
  common: {
    none: "–",
    showJson: "Xem JSON",
    close: "Đóng",
    noData: "Không có dữ liệu",
  },
} as const;

export const t = vi;
